spring.application.name=ryan-api
spring.datasource.url=jdbc:h2:mem:bibliotecafacil
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop

integracao.brasilapi.url=https://brasilapi.com.br
spring.cloud.openfeign.client.config.brasilApiIsbnClient.connectTimeout=3000
spring.cloud.openfeign.client.config.brasilApiIsbnClient.readTimeout=5000
